## YAML Template.
---
spring:
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password:
    h2:
        console:
            enabled: true
            path: /h2
                       

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming:
                strategy: org.hibernate.cfg.ImproveNamingStrategy
        properties:
                hibernate:
                    dialect: org.hibernate.dialect.H2Dialect
                    
                        
                
                   
            
            